/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_crypto_algo_neoscrypt_hasher */

#ifndef _Included_com_google_feathercoin_crypto_hasher

#define _Included_com_google_feathercoin_crypto_hasher
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_crypto_algo_neoscrypt_hasher
 * Method:    neoscrypt
 * Signature: ([C[CI)[C
 */
JNIEXPORT jbyteArray JNICALL Java_com_google_feathercoin_crypto_hasher_neoscrypt
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
